#!/bin/bash

echo SWITCH OFF DISPLAY
export DISPLAY=
echo DISPLAY = $DISPLAY

cd /afs/cern.ch/user/d/donega/work/CMSSW_6_1_0/test/trackerZeroMaterial
eval `scramv1 runtime -sh`

cmsRun SingleGammaPt5-50_cfi_py_GEN_SIM_DIGI_L1_DIGI2RAW_RAW2DIGI_L1Reco_RECO_GRID.py  $1 > output_photon_$1.log

echo "SETTING UP EOS"

source /afs/cern.ch/project/eos/installation/cms/etc/setup.sh

echo "COPYING FILES"
xrdcp /tmp/donega/SingleGammaPt5-50_cfi_py_GEN_SIM_DIGI_L1_DIGI2RAW_RAW2DIGI_L1Reco_RECO_$1.root root://eoscms//eos/cms/store/user/donega/ParticleGun610/Photon/zeroMaterial/SingleGammaPt5-50_cfi_py_GEN_SIM_DIGI_L1_DIGI2RAW_RAW2DIGI_L1Reco_RECO_$1.root

xrdcp output_photon_$1.log root://eoscms//eos/cms/store/user/donega/ParticleGun610/Photon/zeroMaterial/logs/output_photon_$1.log

rm /tmp/donega/SingleGammaPt5-50_cfi_py_GEN_SIM_DIGI_L1_DIGI2RAW_RAW2DIGI_L1Reco_RECO_$1.root
rm output_photon_$1.log

echo "DONE"
